### ISSUE TITLE
Remove git branchhealth command

### ISSUE THREAD

**Issue by jwir3** [jwir3/gitbranchhealth#25]
This command has been deprecated and replaced by git branch-health, which is more readable (#17). In the 1.0 release we should remove git branchhealth as a link to this command.

**Comment by jwir3** [comment]
I'm currently getting the following exception after installing `gitbranchhealth` from pip using:

```
$ sudo pip install gitbranchhealth
```

```
$ git branch-health
Traceback (most recent call last):
  File "/usr/local/bin/git-branch-health", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2793, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: gitbranchhealth==0.2.2
```

This will need to be resolved prior to this ticket landing.

**Comment by jwir3** [comment]
Note that the bug explained in the previous comment appears to be working on the current trunk.
